### ISSUE TITLE
Things which are not working on SFIP for students

### ISSUE THREAD

**Issue by mangalsakshi** [ankit-m/daiict-sen-team-13#13]
1. 'Remove' is not working while editing profile. On clicking it shows a blank page.
2. On clicking 'SFIP', does not navigate to home page.
3. Navigation is not working from profile page.
4. 'Save' option not available on profile page.
5. There is no way to save location and contact.
6. It accepts the job request without filling any details in the form.
7. Logout is working from chatroom page and home page only.

**Comment by ankit-m** [comment]
- [x] 1. 'Remove' is not working while editing profile. On clicking it shows a blank page.
- [x] 2. On clicking 'SFIP', does not navigate to home page.
- [x] 3. Navigation is not working from profile page.
- [x] 4. 'Save' option not available on profile page.
- [x] 5. There is no way to save location and contact.
- [x] 6. It accepts the job request without filling any details in the form.
- [x] 7. Logout is working from chatroom page and home page only.
