### ISSUE TITLE
Regarding a professor's profile

### ISSUE THREAD

**Issue by malav4994** [ankit-m/daiict-sen-team-13#14]
1. can't logout from any of the pages.
2. no 'save' button kind of thing on profile page
3. what 'no. of slots' mean is not clear while opening a new chatroom
4. no. of hours for a specific chat room?
5. any button has no glory of 'open in new tab'.
6. can't open room from the page 'chat rooms'. can open from the only home page.
7. multiple copies of a user (student) when leaves once, and joins again.
8. when i (prof) leave the room, the page opens with all the chatrooms' list (which is not the same as the page 'chatrooms'. I guess it's the page that should open when i click 'all chat rooms' (same as on jobs page)
9. that reminds 'all chat rooms' button isn't working
[things are fine for jobs page]
10. notification wasnt received by the applicant for acceptance.
11. can apply again, after being accepted.
12. home page pe 'show all jobs' isn't working
13. Ankit, u received a msg when i deleted a job (in which u were accepted)?
14. doesnt give a damn about application deadline (creating a job)

**Comment by ankit-m** [comment]
- [x] 1. Logout working
- [x] 2. Save button is not required. Saves automatically
- [ ] 3. Suggest another name
- [x] 4. added end time
- [x] 5. Please write legibly and kindly refrain from using rhetoric. It is a single page application and does not need open in a new tab.
- [x] 6. Fixed
- [x] 7. Fixed
- [x] 8. Cannot understand the issue.
- [x] 9. Fixed
- [x] 10. Looks fine to me. Can  you reproduce the error?
- [x] 11. Works
- [x] 12. Fixed
- [x] 13. The job is deleted i dont see the posting anymore
- [x] 14. Will fix
